
export const ADMIN_UPDATE_FORM = 'ADMIN_UPDATE_FORM'
export const ADMIN_UPDATE_FORM_FULFILLED = 'ADMIN_UPDATE_FORM_FULFILLED'
export const ADMIN_UPDATE_FORM_PENDING = 'ADMIN_UPDATE_FORM_PENDING'
export const ADMIN_UPDATE_FORM_REJECTED = 'ADMIN_UPDATE_FORM_PENDING'

export const ADMIN_CHANGE_ROLE = 'ADMIN_CHANGE_ROLE'
export const ADMIN_CHANGE_ROLE_FULFILLED = 'ADMIN_CHANGE_ROLE_FULFILLED'
export const ADMIN_CHANGE_ROLE_PENDING = 'ADMIN_CHANGE_ROLE_PENDING'
export const ADMIN_CHANGE_ROLE_REJECTED = 'ADMIN_CHANGE_ROLE_REJECTED'

export const ADMIN_ADD_CATEGORIE = 'ADMIN_ADD_CATEGORIE'
export const ADMIN_ADD_CATEGORIE_FULFILLED = 'ADMIN_ADD_CATEGORIE_FULFILLED'
export const ADMIN_ADD_CATEGORIE_PENDING = 'ADMIN_ADD_CATEGORIE_PENDING'
export const ADMIN_ADD_CATEGORIE_REJECTED = 'ADMIN_ADD_CATEGORIE_REJECTED'


export const ADMIN_DELETE_CAT = 'ADMIN_DELETE_CAT'
export const ADMIN_DELETE_CAT_FULFILLED = 'ADMIN_DELETE_CAT_FULFILLED'
export const ADMIN_DELETE_CAT_PENDING = 'ADMIN_DELETE_CAT_PENDING'
export const ADMIN_DELETE_CAT_REJECTED = 'ADMIN_DELETE_CAT_REJECTED'


export const ADMIN_CHANGE_ACCOUNT_ACTIV = 'ADMIN_CHANGE_ACCOUNT_ACTIV'
export const ADMIN_CHANGE_ACCOUNT_ACTIV_FULFILLED = 'ADMIN_CHANGE_ACCOUNT_ACTIV_FULFILLED'
export const AADMIN_CHANGE_ACCOUNT_ACTIV_PENDING = 'ADMIN_CHANGE_ACCOUNT_ACTIV_PENDING'
export const ADMIN_CHANGE_ACCOUNT_ACTIV_REJECTED = 'ADMIN_CHANGE_ACCOUNT_ACTIV_REJECTED'