
export const USER_CONNECT = 'USER_CONNECT'
export const USER_CONNECT_FULFILLED = 'USER_CONNECT_FULFILLED'
export const USER_CONNECT_PENDING = 'USER_CONNECT_PENDING'
export const USER_CONNECT_REJECTED = "USER_CONNECT_REJECTED"

export const USER_AUTH = "USER_AUTH"
export const USER_AUTH_FULFILLED = "USER_AUTH_FULFILLED"
export const USER_AUTH_PENDING = "USER_AUTH_PENDING"
export const USER_AUTH_REJECTED = "USER_AUTH_REJECTED"

export const USER_DISCONNECT = 'USER_CONNECT'
export const USER_DISCONNECT_FULFILLED = 'USER_CONNECT_FULFILLED'
export const USER_DISCONNECT_PENDING = 'USER_CONNECT_PENDING'
export const USER_DISCONNECT_REJECTED = 'USER_DISCONNECT_REJECTED'
