export const RESSOURCE = "RESSOURCE";
export const RESSOURCE_FULFILLED = "RESSOURCE_FULFILLED";
export const RESSOURCE_PENDING = "RESSOURCE_PENDING";
export const RESSOURCE_REJECTED = "RESSOURCE_REJECTED";

export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const ADD_RESSOURCE_FULFILLED = "ADD_RESSOURCE_FULFILLED";
export const ADD_RESSOURCE_PENDING = "ADD_RESSOURCE_PENDING";
export const ADD_RESSOURCE_REJECTED = "ADD_RESSOURCE_REJECTED";

export const GET_RESSOURCE_BY_ID = "GET_RESSOURCE_BY_ID";
export const GET_RESSOURCE_BY_ID_FULFILLED = "GET_RESSOURCE_BY_ID_FULFILLED";
export const GET_RESSOURCE_BY_ID_PENDING = "GET_RESSOURCE_BY_ID_PENDING";
export const GET_RESSOURCE_BY_ID_REJECTED = "GET_RESSOURCE_BY_ID_REJECTED";

export const GET_COMMENT_BY_RESSOURCE_ID = "GET_COMMENT_BY_RESSOURCE_ID";
export const GET_COMMENT_BY_RESSOURCE_ID_FULFILLED = "GET_COMMENT_BY_RESSOURCE_ID_FULFILLED";
export const GET_COMMENT_BY_RESSOURCE_ID_PENDING = "GET_COMMENT_BY_RESSOURCE_ID_PENDING";
export const GET_COMMENT_BY_RESSOURCE_ID_REJECTED = "GET_COMMENT_BY_RESSOURCE_ID_REJECTED";

export const ADD_COMMENT_TO_RESSOURCE = "ADD_COMMENT_TO_RESSOURCE";
export const ADD_COMMENT_TO_RESSOURCE_FULFILLED = "ADD_COMMENT_TO_RESSOURCE_FULFILLED";
export const ADD_COMMENT_TO_RESSOURCE_PENDING = "ADD_COMMENT_TO_RESSOURCE_PENDING";
export const ADD_COMMENT_TO_RESSOURCE_REJECTED = "ADD_COMMENT_TO_RESSOURCE_REJECTED";

export const ADD_TO_FAVORIS = "ADD_TO_FAVORIS";
export const ADD_TO_FAVORIS_FULFILLED = "ADD_TO_FAVORIS_FULFILLED";
export const ADD_TO_FAVORIS_PENDING = "ADD_TO_FAVORIS_PENDING";
export const ADD_TO_FAVORIS_REJECTED = "ADD_TO_FAVORIS_REJECTED";

export const REMOVE_FROM_FAVORIS = "REMOVE_FROM_FAVORIS";
export const REMOVE_FROM_FAVORIS_FULFILLED = "REMOVE_FROM_FAVORIS_FULFILLED";
export const REMOVE_FROM_FAVORIS_PENDING = "REMOVE_FROM_FAVORIS_PENDING";
export const REMOVE_FROM_FAVORIS_REJECTED = "REMOVE_FROM_FAVORIS_REJECTED";

export const GET_ALL_FAVORIS_BY_USER_ID = "GET_ALL_FAVORIS_BY_USER_ID";
export const GET_ALL_FAVORIS_BY_USER_ID_FULFILLED = "GET_ALL_FAVORIS_BY_USER_ID_FULFILLED";
export const GET_ALL_FAVORIS_BY_USER_ID_PENDING = "GET_ALL_FAVORIS_BY_USER_ID_PENDING";
export const GET_ALL_FAVORIS_BY_USER_ID_REJECTED = "GET_ALL_FAVORIS_BY_USER_ID_REJECTED";

export const DELETE_RESSOURCE_BY_ID = "DELETE_RESSOURCE_BY_ID";
export const DELETE_RESSOURCE_BY_ID_FULFILLED = "DELETE_RESSOURCE_BY_ID_FULFILLED";
export const DELETE_RESSOURCE_BY_ID_PENDING = "DELETE_RESSOURCE_BY_ID_PENDING";
export const DELETE_RESSOURCE_BY_ID_REJECTED = "DELETE_RESSOURCE_BY_ID_REJECTED";
