export const RESSOURCE = "RESSOURCE";
export const RESSOURCE_FULFILLED = "RESSOURCE_FULFILLED";
export const RESSOURCE_PENDING = "RESSOURCE_PENDING";
export const RESSOURCE_REJECTED = "RESSOURCE_REJECTED";

export const ADD_RESSOURCE = "ADD_RESSOURCE";
export const ADD_RESSOURCE_FULFILLED = "ADD_RESSOURCE_FULFILLED";
export const ADD_RESSOURCE_PENDING = "ADD_RESSOURCE_PENDING";
export const ADD_RESSOURCE_REJECTED = "ADD_RESSOURCE_REJECTED";