export const RESSOURCE = "RESSOURCE";
export const RESSOURCE_FULFILLED = "RESSOURCE_FULFILLED";
export const RESSOURCE_PENDING = "RESSOURCE_PENDING";
export const RESSOURCE_REJECTED = "RESSOURCE_REJECTED";