export const USER_GET_PROFIL = 'USER_CONNECT'
export const USER_GET_PROFIL_FULFILLED = 'USER_CONNECT_FULFILLED'
export const USER_GET_PROFIL_PENDING = 'USER_CONNECT_PENDING'

export const SET_USER_ROLE = "SET_USER_ROLE"
export const SET_USER = "SET_USER"
